language: python
python:
  - '3.6.8'

before_script:
  - pip install -r pbapp/requirements.txt



services:
  - postgresql
env: DJANGO_SETTINGS_MODULE="settings.travis"
script:
  - cd pbapp
  - python manage.py test
