language: python
python:
  - '3.6.8'

before_script:
  - pip install -r pbapp/requirements.txt



services:
  - postgresql
env: DJANGO_SETTINGS_MODULE="pbapp.settings.travis"
script:
  - python pbapp/manage.py test
