language: python
python:
  - '3'

before_script:
  - pip install -r requirements.txt

env: DJANGO_SETTINGS_MODULE="settings"

services:
  - postgresql

script:
  - ./manage.py test

branches:
  only:
    - dply
